In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import decomposition

#https://stackabuse.com/implementing-pca-in-python-with-scikit-learn/
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier



In [7]:

names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
                      , names=names)

In [8]:
df.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [25]:
#single variable PCA 


#split the features and labels
X = df.drop('Class', 1)
y = df['Class']

# Splitting the dataset into the Training set and Test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#this normalise the dataset - see notes 

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#this performs a PCA for each variable in the dataset
#note its overwriting X_train, you will need to fun from 3 cells up to restart
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

#not exactly sure why we need to name this process
explained_variance = pca.explained_variance_ratio_
#display(explained_variance)

#single variable PCA 

pca = PCA(n_components=1)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
display(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0 12  1]
 [ 0  1  5]]


0.9333333333333333

In [26]:
#two variable PCA 


#split the features and labels
X = df.drop('Class', 1)
y = df['Class']

# Splitting the dataset into the Training set and Test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#this normalise the dataset - see notes 

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#this performs a PCA for each variable in the dataset
#note its overwriting X_train, you will need to fun from 3 cells up to restart
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

#not exactly sure why we need to name this process
explained_variance = pca.explained_variance_ratio_
#display(explained_variance)

#single variable PCA 

pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
display(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0  9  4]
 [ 0  2  4]]


0.8

In [27]:
#three variable PCA 


#split the features and labels
X = df.drop('Class', 1)
y = df['Class']

# Splitting the dataset into the Training set and Test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#this normalise the dataset - see notes 

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#this performs a PCA for each variable in the dataset
#note its overwriting X_train, you will need to fun from 3 cells up to restart
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

#not exactly sure why we need to name this process
explained_variance = pca.explained_variance_ratio_
#display(explained_variance)

#single variable PCA 

pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
display(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0  8  5]
 [ 0  1  5]]


0.8

In [28]:
#all variable PCA 


#split the features and labels
X = df.drop('Class', 1)
y = df['Class']

# Splitting the dataset into the Training set and Test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#this normalise the dataset - see notes 

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#this performs a PCA for each variable in the dataset
#note its overwriting X_train, you will need to fun from 3 cells up to restart
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

#not exactly sure why we need to name this process
explained_variance = pca.explained_variance_ratio_
#display(explained_variance)

#single variable PCA 

pca = PCA(n_components=4)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
display(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0 11  2]
 [ 0  1  5]]


0.9